### ISSUE TITLE
Problems accessing the repository from a Moodle 3.9

### ISSUE THREAD

**Issue by raquelcascales** [lucisgit/moodle-repository_panopto#10]
Hi,
We have installed both repository and ressource plugins on our Moodle 3.9.
I can find the repository but when I try to open it and navigate it is not working. If I introduce manually the "Delivery ID" it works and the video is displayed.

Here you have a screenshot of the file picker:
![image](https://github.com/lucisgit/moodle-repository_panopto/assets/167536199/f35b87de-8bd7-430f-b5ef-9beed43dd44a)

When I edit the activity, the following error message appears:
invalidresponse
Invalid response value detected

Any idea why this is happening?

Thanks a lot!
Raquel.

**Comment by tonyjbutler** [comment]
Assuming this is a development/testing site, you should be able to get some more information (ideally a stack trace) into the 'invalidresponse' message, if you set 'Debug messages' to 'Developer' level and enable 'Display debug messages' (in Site administration -> Development -> Debugging). If this is not a dev site and you don't have access to one, then you may be able to find a more detailed message in the web server error log.

**Comment by tonyjbutler** [comment]
@raquelcascales Did you manage to get any more info on this error?

**Comment by raquelcascales** [comment]
Hi Tony,

We finally chose another tool for our video repository and we don't need to make this plugin work anymore.
But thanks a lot for your help.

Best regards,

RENAC Online: New courses starting on 1 April and 1 October - check our website!<https://www.renac.de/trainings-services/trainings/renac-online/>
Renewables Academy (RENAC) AG
Raquel Cascales (Ms)
Project Director eLearning & Blended Learning


***@***.***

-------------------------------------------------------------------
Schoenhauser Allee 10-11, 10119 Berlin, Germany
Tel: +49 (0)30 587 08 70 46 | Fax: +49 (0)30 587 0870 88
E-Mail: ***@***.******@***.***>
www.renac.de<http://www.renac.de/> | Newsletter<https://www.renac.de/newsletter-sign-up/> | LinkedIn<https://www.linkedin.com/company/renewables-academy-ag-renac-> | Facebook<https://www.facebook.com/RENAC> | Twitter<https://twitter.com/renac_ag> | YouTube<https://www.youtube.com/channel/UCbTbrHnvi4AF7qZP64fwGYg>
CEO: Berthold Breid | Chairman of the supervisory board: Dr. Paul Grunow | VAT No.: DE258659985 | Tax ID: 30/103/76334 | HRB 111 679 | District court Charlottenburg
***@***.***



Von: Tony Butler ***@***.***>
Gesendet: Freitag, 31. Mai 2024 13:37
An: lucisgit/moodle-repository_panopto ***@***.***>
Cc: Raquel Cascales ***@***.***>; Mention ***@***.***>
Betreff: Re: [lucisgit/moodle-repository_panopto] Problems accessing the repository from a Moodle 3.9 (Issue #10)


@raquelcascales<https://github.com/raquelcascales> Did you manage to get any more info on this error?

-
