### ISSUE TITLE
Moodle username is passed to panopto

### ISSUE THREAD

**Issue by danmarsden** [lucisgit/moodle-repository_panopto#3]
https://github.com/lucisgit/moodle-repository_panopto/blob/master/externallib.php#L75

Generally it's bad practice to send the username to an external service as it is part of the users authentication credentials. Is this required? - could you look at using something else here instead?

**Comment by kabalin** [comment]
Hi Dan, the thing is that Panopto is using Moodle as identity provider (and for SSO), so usernames in Moodle and Panopto are the same (with instance prefix added as you see in the code), therefore  passing username is a valid thing to do. Anyway, well spotted 😉 !

**Comment by danmarsden** [comment]
cool - that will need to be documented in the plugins db entry under the "Potential privacy issues" area - to specify that the moodle username is passed to the external system. 
Usually it's preferably to use the "email" address rather than the "username" field but that isn't always possible. (even though in many cases this is either exactly the same or similar to the username field.)

**Comment by kabalin** [comment]
> that will need to be documented in the plugins db entry under the "Potential privacy issues" area - to specify that the moodle username is passed to the external system.

Thanks for advise Dan, I have just done it.
