### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by danmarsden** [lucisgit/moodle-repository_panopto#4]
the files in /lib/panopto/lib/Panopto/PublicAPI/4.6 appear to be missing the licence and attribution information. I see that the Lancaster written client files are licensed as gpl, but it's not clear where the other files come from, who wrote them, who copyright is assigned to or what license they are actually released under.

Can you please clarify this? - (this is a blocker for approval in the plugins db.)

**Comment by kabalin** [comment]
Files located at /lib/panopto/lib/Panopto/PublicAPI/4.6 are automatically generated using tool called `wsdl2phpgenerator` (that is basically producing PHP classes using Panopto WSDL interface endpoints as data source). It is all within https://github.com/lucisgit/php-panopto-api repo with instruction on usage.

**Comment by danmarsden** [comment]
cool - probably just needs something added to a readme file in the lib/panopto folder? - with a link to the external repo and mentioning the licensing info.

**Comment by kabalin** [comment]
Thanks Dan, I addressed this at https://github.com/lucisgit/moodle-repository_panopto/commit/be66ff8abb8747c19b843a5c52fe0433ff3ebfff
