### ISSUE TITLE
Review use of param_raw

### ISSUE THREAD

**Issue by danmarsden** [lucisgit/moodle-repository_panopto#6]
I see quite a few PARAM_RAW and PARAM_RAW_TRIMMED that look like they can probably be more restrictive - it might be worth reviewing these (feel free to close as won't fix if you really need RAW vars..)

**Comment by kabalin** [comment]
Hi Dan, thanks for reporting this. Issue has been addressed in https://github.com/lucisgit/moodle-repository_panopto/commit/c39946b9ca646abd1c5180af75d795ac04a884b5
