### ISSUE TITLE
is the repository plugin useful without the module?

### ISSUE THREAD

**Issue by danmarsden** [lucisgit/moodle-repository_panopto#8]
I see you present a warning when the module is not installed, but does the plugin make sense when the module is not installed? - if it doesn't make sense to only have the repository plugin you might want to add a dependency in version.php for the activity. (feel free to close if you think there is a use-case for just installing the repository.)

**Comment by kabalin** [comment]
No, it is not useful without module, and the opposite is true in fact. Will add a dependency.

**Comment by kabalin** [comment]
Issue has been addressed at https://github.com/lucisgit/moodle-repository_panopto/commit/f84d782670bf7f4f09e5a38eadbf24c4a08ec860
